/**
 * Generated by "@vuepress/internal-root-mixins"
 */
import m0 from "D:\\me\\vue\\vuepress\\front-end-interview\\node_modules\\_@vuepress_core@1.2.0@@vuepress\\core\\lib\\client\\root-mixins\\updateMeta.js"
import m1 from "D:\\me\\vue\\vuepress\\front-end-interview\\node_modules\\_@vuepress_plugin-active-header-links@1.2.0@@vuepress\\plugin-active-header-links\\clientRootMixin.js"
import m2 from "D:\\me\\vue\\vuepress\\front-end-interview\\node_modules\\_@vuepress_plugin-nprogress@1.2.0@@vuepress\\plugin-nprogress\\clientRootMixin.js"
import m3 from "D:\\me\\vue\\vuepress\\front-end-interview\\node_modules\\_@vuepress_plugin-medium-zoom@1.2.0@@vuepress\\plugin-medium-zoom\\clientRootMixin.js"

export default [
  m0,
  m1,
  m2,
  m3
]