/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\me\\vue\\vuepress\\front-end-interview\\node_modules\\_@vuepress_core@1.2.0@@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-0c9ba8da",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c9ba8da").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-743b8ab4",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-743b8ab4").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-342fcfcf",
    path: "/guide/book.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-342fcfcf").then(next)
    },
  },
  {
    name: "v-0f12bd3b",
    path: "/guide/babel.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0f12bd3b").then(next)
    },
  },
  {
    name: "v-76ad6f4b",
    path: "/guide/common.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-76ad6f4b").then(next)
    },
  },
  {
    name: "v-0bbee04a",
    path: "/guide/composite.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0bbee04a").then(next)
    },
  },
  {
    name: "v-35d59dc2",
    path: "/guide/designPatterns.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-35d59dc2").then(next)
    },
  },
  {
    name: "v-50a641ca",
    path: "/guide/dataStructure.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-50a641ca").then(next)
    },
  },
  {
    name: "v-1ff9930a",
    path: "/guide/dom.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1ff9930a").then(next)
    },
  },
  {
    name: "v-6261258a",
    path: "/guide/framework.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6261258a").then(next)
    },
  },
  {
    name: "v-f1de0a3a",
    path: "/guide/hoisting.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f1de0a3a").then(next)
    },
  },
  {
    name: "v-1f9d235b",
    path: "/guide/httpWritten.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1f9d235b").then(next)
    },
  },
  {
    name: "v-5939009d",
    path: "/guide/node.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5939009d").then(next)
    },
  },
  {
    name: "v-6ed0838a",
    path: "/guide/preface.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6ed0838a").then(next)
    },
  },
  {
    name: "v-4a7b4302",
    path: "/guide/string.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4a7b4302").then(next)
    },
  },
  {
    name: "v-7b9dbefb",
    path: "/guide/webpackPluginDesign.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7b9dbefb").then(next)
    },
  },
  {
    name: "v-7de0ad61",
    path: "/guide/carousel.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7de0ad61").then(next)
    },
  },
  {
    name: "v-6bdc279b",
    path: "/guide/component.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6bdc279b").then(next)
    },
  },
  {
    name: "v-f43c784a",
    path: "/guide/componentCli.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f43c784a").then(next)
    },
  },
  {
    name: "v-49ebc41b",
    path: "/guide/deepclone.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-49ebc41b").then(next)
    },
  },
  {
    name: "v-386044db",
    path: "/guide/engineering.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-386044db").then(next)
    },
  },
  {
    name: "v-6db0333b",
    path: "/guide/event.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6db0333b").then(next)
    },
  },
  {
    name: "v-839c4cca",
    path: "/guide/execute.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-839c4cca").then(next)
    },
  },
  {
    name: "v-1d95074d",
    path: "/guide/hr.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1d95074d").then(next)
    },
  },
  {
    name: "v-2a61b15b",
    path: "/guide/htmlBasic.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2a61b15b").then(next)
    },
  },
  {
    name: "v-50f233bb",
    path: "/guide/immutable.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-50f233bb").then(next)
    },
  },
  {
    name: "v-0a3f6d1b",
    path: "/guide/mechanism.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0a3f6d1b").then(next)
    },
  },
  {
    name: "v-06fcb09f",
    path: "/guide/memory.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-06fcb09f").then(next)
    },
  },
  {
    name: "v-0bde6d1b",
    path: "/guide/project.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0bde6d1b").then(next)
    },
  },
  {
    name: "v-4579e3dd",
    path: "/guide/reactivity.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4579e3dd").then(next)
    },
  },
  {
    name: "v-34a8e60f",
    path: "/guide/router.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-34a8e60f").then(next)
    },
  },
  {
    name: "v-2184f3fa",
    path: "/guide/setState.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2184f3fa").then(next)
    },
  },
  {
    name: "v-50d037fb",
    path: "/guide/vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-50d037fb").then(next)
    },
  },
  {
    name: "v-7128ca9b",
    path: "/guide/webpack.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7128ca9b").then(next)
    },
  },
  {
    name: "v-69f7aedb",
    path: "/guide/webpackMoudle.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-69f7aedb").then(next)
    },
  },
  {
    name: "v-46b848db",
    path: "/guide/algorithm.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-46b848db").then(next)
    },
  },
  {
    name: "v-6bda7de1",
    path: "/guide/WebpackHMR.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6bda7de1").then(next)
    },
  },
  {
    name: "v-16d83e9b",
    path: "/guide/babelPlugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-16d83e9b").then(next)
    },
  },
  {
    name: "v-9f79cd8a",
    path: "/guide/browser.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9f79cd8a").then(next)
    },
  },
  {
    name: "v-76524acb",
    path: "/guide/cssBasic.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-76524acb").then(next)
    },
  },
  {
    name: "v-7663127b",
    path: "/guide/devsProxy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7663127b").then(next)
    },
  },
  {
    name: "v-2db834de",
    path: "/guide/http.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2db834de").then(next)
    },
  },
  {
    name: "v-693cb73b",
    path: "/guide/jsWritten.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-693cb73b").then(next)
    },
  },
  {
    name: "v-214a55db",
    path: "/guide/react.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-214a55db").then(next)
    },
  },
  {
    name: "v-4fe8ad72",
    path: "/guide/resume.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4fe8ad72").then(next)
    },
  },
  {
    name: "v-402c91a1",
    path: "/guide/security.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-402c91a1").then(next)
    },
  },
  {
    name: "v-4f62381b",
    path: "/guide/tcp.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4f62381b").then(next)
    },
  },
  {
    name: "v-09cdba9a",
    path: "/guide/virtualDom.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-09cdba9a").then(next)
    },
  },
  {
    name: "v-170ed8fb",
    path: "/guide/webpackLoader.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-170ed8fb").then(next)
    },
  },
  {
    name: "v-5ac8fedd",
    path: "/guide/abstract.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ac8fedd").then(next)
    },
  },
  {
    name: "v-9f60a30a",
    path: "/guide/ast.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9f60a30a").then(next)
    },
  },
  {
    name: "v-a7036d8a",
    path: "/guide/eventLoop.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a7036d8a").then(next)
    },
  },
  {
    name: "v-246c1b9b",
    path: "/guide/jsBasic.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-246c1b9b").then(next)
    },
  },
  {
    name: "v-15560bbb",
    path: "/guide/reactHook.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15560bbb").then(next)
    },
  },
  {
    name: "v-3b1d460a",
    path: "/guide/webpackPlugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b1d460a").then(next)
    },
  },
  {
    name: "v-6e070d0a",
    path: "/guide/fiber.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e070d0a").then(next)
    },
  },
  {
    name: "v-230ea256",
    path: "/guide/load.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-230ea256").then(next)
    },
  },
  {
    name: "v-c35dab0a",
    path: "/guide/redux.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c35dab0a").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]